/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoPersona.ui;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectoPersona.crud.PersonaCRUD;
import proyectoPersona.modelo.Persona;
import proyectoPersona.ui.ActualizarPersona;

/**
 *
 * @author Kimberly Sumala
 */
public class MostrarPersona extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MostrarPersona.class.getName());
    PersonaCRUD operaciones = new PersonaCRUD();
    /**
     * Creates new form MostrarPersona
     */
    public MostrarPersona() {
        initComponents();
        cargarTabla();
        txtBuscarId.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                if (txtBuscarId.getText().trim().isEmpty()) {
                cargarTabla(); // vuelve a mostrar todo
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tPersona = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBuscarId = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel1.setText("AGREGAR PERSONA");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel2.setText("MOSTRAR PERSONA");

        tPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tPersona);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel3.setText("Selecciona un registro para:");

        jLabel4.setText("Buscar por Id:");

        txtBuscarId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarIdKeyReleased(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnActualizar)
                            .addGap(18, 18, 18)
                            .addComponent(btnEliminar))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int fila = tPersona.getSelectedRow();
        if(fila == -1){
            JOptionPane.showMessageDialog(this,"Seleccione un registro","AVISO", JOptionPane.WARNING_MESSAGE);
        }
        //Se Extraen los valores de la fila o registro que se selecciona
        String id = tPersona.getValueAt(fila, 0).toString();
        String nombre = tPersona.getValueAt(fila, 1).toString();
        String apellido = tPersona.getValueAt(fila, 2).toString();
        int edad = Integer.parseInt(tPersona.getValueAt(fila, 3).toString());
        //Se abre el formulario actualizar con los datos de la fila
        ActualizarPersona actualizar = new ActualizarPersona(id,nombre,apellido,edad);
        actualizar.setVisible(true);
        actualizar.setTitle("ACTUALIZAR PERSONA");
        actualizar.setLocationRelativeTo(null);
        //Cuando la ventana se cierra se recarga la tabla
        actualizar.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
            cargarTabla(); // Refrescar la tabla al cerrar
            }
        });
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try{
            int fila = tPersona.getSelectedRow();
            if(fila==-1){
                JOptionPane.showMessageDialog(this,"Seleccione un Registro","Advertencia",JOptionPane.WARNING_MESSAGE);
            }
            //Se obtiene el id del registro seleccionado
            String id = tPersona.getValueAt(fila, 0).toString();
            
            int confirmar = JOptionPane.showConfirmDialog(this,"¿Desea Eliminar el registro?","Confirmar eliminacion",JOptionPane.YES_NO_OPTION);
            if(confirmar == JOptionPane.YES_OPTION){
                operaciones.eliminarPersona(id);
                cargarTabla();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"ERROR al eliminar Persona"+e.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try{
            String id = txtBuscarId.getText().trim();
            //El text box no este vacio
            if(id.isEmpty()){
                JOptionPane.showMessageDialog(this,"Ingrese un Id para buscar");
            }
            // se obtinen los datos de la base de datos
            Persona p = operaciones.obtenerPersona(id);
            // si no se encuentra el id
            if(p == null){
                JOptionPane.showMessageDialog(this,"No existe la Persona");
            }
            //Tabla muestre solo el resultado con el id
            String[] columnas = {"ID","Nombre","Apellido","Edad"};
            DefaultTableModel modelo = new DefaultTableModel(null, columnas);

            Object[] fila = {p.getId(),p.getNombre(),p.getApellido(),p.getEdad()};
            modelo.addRow(fila);

            tPersona.setModel(modelo);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error al buscar","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed
    

    
    private void txtBuscarIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarIdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarIdKeyReleased

    public void cargarTabla(){
        //Se crean las columnas de la tabla
        String[] columnas = {"ID","Nombre","Apellido","Edad"};
        DefaultTableModel modelo = new DefaultTableModel(null,columnas){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // No permitir editar celdas
            }
        };
        tPersona.setModel(modelo);
        //Se obtienen las personas de BD
        List<Persona> lista = operaciones.consultarPersonas();
        //Se llenan las filas de la tabla
        for(Persona p : lista){
            Object[] fila = {p.getId(),p.getNombre(),p.getApellido(),p.getEdad()};
            modelo.addRow(fila);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tPersona;
    private javax.swing.JTextField txtBuscarId;
    // End of variables declaration//GEN-END:variables
}
